services:
  postgres:
    image: postgres:14
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=bkr
      - POSTGRES_USER=bkr
      - POSTGRES_DB=bkr

volumes:
  data:
